name: backend CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Gave execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

  test-context:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Gave execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --tests com.example.software_testing_lab1.SoftwareTestingLab1ApplicationTests

  test-arcsin:
    needs: test-context
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Gave execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --tests com.example.software_testing_lab1.ArcsinDecompositionServiceTests

  test-bfs:
    needs: test-arcsin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Gave execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --tests com.example.software_testing_lab1.BFSServiceTests

